name: base_bloc
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  google_fonts: ^2.1.0
  flutter_dotenv: ^5.0.0
  flutter_svg: ^0.22.0
  pull_to_refresh: ^2.0.0
  logger: ^1.0.0
  event_bus: ^2.0.0
  get_storage: ^2.0.2  # save data to storage(sharePref)
  intl: ^0.17.0
  get_cli: ^1.7.1
  images_picker:
    git:
      url: https://github.com/truhoada/images_picker.git
      ref: docsify/1.2.11
  cached_network_image: ^3.0.0
  url_launcher: ^6.0.9
  flutter_html: ^2.1.1
  permission_handler: ^8.1.4+2
  package_info: ^2.0.2
  dotted_line: ^3.1.0
  syncfusion_flutter_datepicker: ^19.4.55
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.5.0
  scrollable_positioned_list: ^0.2.3 #custom calendar time line.
  email_validator: ^2.0.1
  fluttertoast: ^8.0.9
  flutter_bloc: ^8.1.1
  #  device_info_plus: ^2.0.1
  device_info: ^2.0.3
  expandable_page_view: ^1.0.14
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: ^1.3.0
  connectivity_plus: ^2.3.0 #internet connection
  flutter_facebook_auth: ^4.3.0
  flutter_datetime_picker: ^1.5.1
  sqflite: ^2.0.2+1
  flutter_typeahead: ^4.0.0
  dropdown_button2: ^1.5.2
  google_maps_flutter: ^2.1.6
  flutter_rating_bar: ^4.0.1
  youtube_player_flutter: ^8.1.0
  diacritic: ^0.1.3
  back_button_interceptor: ^6.0.1
  weekly_date_picker: ^1.3.0
  firebase_dynamic_links: ^4.3.1
  flutter_share: ^2.0.0
  dio: ^4.0.6

dev_dependencies:
  build_runner:
  flutter_gen_runner:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
     - assets/svg/
     - assets/png/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
